steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/test-xepelin/vank-api-v1', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/test-xepelin/vank-api-v1']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'vank-api',
        '--image',
        'gcr.io/test-xepelin/vank-api-v1',
        '--region',
        'us-central1',
      ]
images:
  - gcr.io/test-xepelin/vank-api-v1
